# DELETE http://localhost:3001/api/persons/4
DELETE https://exercisesbackendpart3.fly.dev/api/persons/4

###
# GET http://localhost:3001/api/persons
GET https://exercisesbackendpart3.fly.dev/api/persons